main:
  name: DatasetPolicyTester
  batchedPolicyPlayer: $x0
  datasetFile: /ImbaKeks/git/MasterThesis/src/datasets/connect4/p6_weak_big.dataset
  initialGameState: $mnk
  mode: shell
  batchSize: 128

updater:
  name: FilePolicyUpdater
  path: /ImbaKeks/x0/best.network

x0:
  name: PolicyIteratorPlayer
  policy: $resnet
  policyIterator: $mcts
  policyUpdater: $updater
  moveDecider: $bestMoves
  batchSize: 128

optimizerArgs:
  name: dict
  lr: 0.001
  weight_decay: 0.0001

resnet:
  name: PytorchPolicy
  batchSize: 128
  blocks: 5
  filters: 128
  headKernel: 3
  headFilters: 64
  extraHeadFilters: 32
  protoState: $mnk
  device: cuda
  optimizerName: torch.optim.adamw.AdamW
  optimizerArgs: $optimizerArgs

mcts:
  name: MctsPolicyIterator
  expansions: 8
  cpuct: 3
  rootNoise: 0.001
  drawValue: 0.4

bestMoves:
  name: TemperatureMoveDecider
  explorationPlyCount: -1

mnk:
  name: Connect4GameState
  m: 7
  n: 6
  k: 4
