reporter:
  name: SingleProcessReporter
  windowSize: 300000
  reportsPerIteration: 45000
  state: /ImbaKeks/runs/connect4

updater:
  name: SingleProcessUpdater
  trainEpochs: 2
  state: /ImbaKeks/runs/connect4

mnk:
  name: Connect4GameState
  m: 7
  n: 6
  k: 4

optimizerArgs:
  name: dict
  lr: 0.2
  momentum: 0.9
  weight_decay: 0.0001

lrschedule:
  name: LrStepSchedule
  startValue: 0.2
  stepEvery: 10
  stepMultiplier: 0.1
  minValue: 0.01

resnet:
  name: PytorchPolicy
  batchSize: 128
  blocks: 3
  filters: 64
  headKernel: 3
  headFilters: 64
  extraHeadFilters: 32
  protoState: $mnk
  device: cuda:0
  optimizerName: torch.optim.SGD
  optimizerArgs: $optimizerArgs
  gradClipValue: 1
  lrDecider: $lrschedule

bestMcts:
  name: MctsPolicyIterator
  expansions: 40
  cpuct: 1.5
  rootNoise: 0.001
  drawValue: 0.4
  alphaBase: 10.0
  fpu: 0

mcts:
  name: MctsPolicyIterator
  expansions: 200
  cpuct: 1.5
  rootNoise: 0.2
  drawValue: 0.4
  alphaBase: 10.0
  fpu: 0

bestMoves:
  name: TemperatureMoveDecider
  explorationPlyCount: -1

tempDecider:
  name: TemperatureMoveDecider
  explorationPlyCount: 20

main:
  name: LinearSelfPlayWorker
  initialState: $mnk
  policy: $resnet
  policyIterator: $mcts
  gameCount: 128
  moveDecider: $tempDecider
  gameReporter: $reporter
  policyUpdater: $updater
