feature_provider:
  name: ResCNN
  inWidth: 6
  inHeight: 7
  inDepth: 1
  baseKernelSize: 3
  baseFeatures: 128
  features: 32
  blocks: 3
  moveSize: 7
  winSize: 3
  extraHeadFilters: 1
  mode: sq
  outputExtra: bothhead


main:
  name: SupervisedNetworkTrainer
  datasetFile: datasets/connect4/1M_future.txt.zip
  initialGame: $c4
  policy: $resnet
  windowSizeSplits: 1
  trainingRuns: 5
  workingDirectory: /PwnKeks/x0/supervised/future_move1
  testSamples: 100000
  validationSamples: 100000
  batchSize: 128
  lrStart: 0.2
  lrPatience: 8
  featureProvider: $feature_provider
  featureNetwork: f7b37c26-9568-4789-a996-5d662000f91f.network

c4:
  name: Connect4GameState
  m: 7
  n: 6
  k: 4

optimizerArgs:
  name: dict
  lr: 0.2
  momentum: 0.9
  weight_decay: 0.0001

resnet:
  name: PytorchPolicy
  batchSize: 128
  blocks: 5
  filters: 128
  headKernel: 3
  headFilters: 64
  extraHeadFilters: 32
  networkMode: sq
  protoState: $c4
  device: cuda
  optimizerName: torch.optim.SGD
  optimizerArgs: $optimizerArgs
  gradClipValue: 1
  useWinFeatures: -1
  useMoveFeatures: 1
  featuresWeight: 1