# Run Name: rgb_network
# Run ID:  47e9fd6f-6113-4d42-b3da-07d04a65f80a
# Run SHA: 1fc8f1cfe925a01d390683fb98a0659cedd0321e
reporter:
  name: DistributedReporter
  packageSize: 1024

updater:
  name: DistributedNetworkUpdater2
  storage: /tmp/x0_networks

mnk:
  name: Connect4GameState
  m: 7
  n: 6
  k: 4

optimizerArgs:
  name: dict
  weight_decay: 0.0001
  momentum: 0.9
  lr: 0.2

lrcycle:
  name: OneCycleSchedule
  peak: 0.35
  end: 0.7
  baseVal: 0.02
  peakVal: 0.2
  endVal: 0.003
  dbgName: lr
  targetIteration: 20
  targetReductionFactor: 0.4

momentumcycle:
  name: OneCycleSchedule
  peak: 0.35
  end: 0.7
  baseVal: 0.95
  peakVal: 0.85
  endVal: 0.95
  dbgName: momentum

resnet:
  name: PytorchPolicy
  batchSize: 1024
  blocks: 1
  filters: 16
  headKernel: 3
  headFilters: 64
  extraHeadFilters: 3
  protoState: $mnk
  silent: true
  device: cuda
  lrDecider: $lrcycle
  momentumDecider: $momentumcycle
  optimizerName: torch.optim.SGD
  optimizerArgs: $optimizerArgs
  gradClipValue: 1
  valueLossWeight: 0.01
  networkMode: sq
  replyWeight: 0

mcts:
  name: MctsPolicyIterator
  expansions: 343
  cpuct: 1.545
  rootNoise: 0.25
  drawValue: 0.6913
  alphaBase: 20.38
  fpu: 0.8545

tempDecider:
  name: TemperatureMoveDecider
  explorationPlyCount: 30

worker:
  name: LinearSelfPlayWorker
  initialState: $mnk
  policy: $resnet
  policyIterator: $mcts
  gameCount: 1024
  moveDecider: $tempDecider
  gameReporter: $reporter
  policyUpdater: $updater

trainerWindow:
  name: SlowWindowSizeManager
  startSize: 500000
  growStart: 5
  growFinish: 15
  finalSize: 2000000
  iterationSize: 180000
  minimumSize: 8192

trainer:
  name: StreamTrainingWorker2
  windowManager: $trainerWindow
  policy: $resnet
  batchSize: 1024
  deduplicate: True
  deduplicationWeight: 0.8
