# Run Name: playout_cap_test_3
# Run ID:  997f4d2d-5546-401b-b0f5-39012158894e
# Run SHA: 3a74516f3c49dd2209994b3354de515332fa6d26
reporter:
  name: DistributedReporter
  packageSize: 1024

updater:
  name: DistributedNetworkUpdater2
  storage: /tmp/x0_networks

mnk:
  name: Connect4GameState
  m: 7
  n: 6
  k: 4

optimizerArgs:
  name: dict
  weight_decay: 0.0001
  momentum: 0.9
  lr: 0.2

lrschedule:
  name: LrStepSchedule
  startValue: 0.2
  stepEvery: 7
  stepMultiplier: 0.1
  minValue: 0.002

resnet:
  name: PytorchPolicy
  batchSize: 256
  blocks: 5
  filters: 128
  headKernel: 3
  headFilters: 64
  extraHeadFilters: 32
  protoState: $mnk
  silent: true
  device: cuda
  lrDecider: $lrschedule
  optimizerName: torch.optim.SGD
  optimizerArgs: $optimizerArgs
  gradClipValue: 1
  valueLossWeight: 0.01

mcts:
  name: MctsPolicyIterator
  expansions: 343
  cpuct: 1.545
  rootNoise: 0.25
  drawValue: 0.6913
  alphaBase: 20.38
  fpu: 0.8545

cheapMcts:
  name: MctsPolicyIterator
  expansions: 34
  cpuct: 1.545
  rootNoise: 0.025
  drawValue: 0.5
  alphaBase: 20.38
  fpu: 0

tempDecider:
  name: TemperatureMoveDecider
  explorationPlyCount: 30

cheapPlayDecider:
  name: TemperatureMoveDecider
  explorationPlyCount: 10

worker:
  name: LinearSelfPlayWorker
  initialState: $mnk
  policy: $resnet
  policyIterator: $mcts
  gameCount: 256
  moveDecider: $tempDecider
  capPolicyP: 0.75
  capPolicyIterator: $cheapMcts
  capMoveDecider: $cheapPlayDecider
  gameReporter: $reporter
  policyUpdater: $updater

trainerWindow:
  name: ConstantWindowSizeManager
  size: 2000000
  minimumSize: 8192
  iterationSize: 300000

trainer:
  name: StreamTrainingWorker2
  windowManager: $trainerWindow
  policy: $resnet
  batchSize: 1024