reporter:
  name: SingleProcessReporter
  windowSize: 10000
  reportsPerIteration: 3000
  state: /ImbaKeks/runs/mnk333_0

updater:
  name: SingleProcessUpdater
  trainEpochs: 2
  state: /ImbaKeks/runs/mnk333_0

mnk:
  name: MNKGameState
  m: 3
  n: 3
  k: 3

optimizerArgs:
  name: dict
  lr: 0.001
  weight_decay: 0.0001

resnet:
  name: PytorchPolicy
  batchSize: 128
  blocks: 1
  filters: 64
  headKernel: 3
  headFilters: 64
  protoState: $mnk
  device: cuda:0
  optimizerName: torch.optim.adamw.AdamW
  optimizerArgs: $optimizerArgs

mcts:
  name: MctsPolicyIterator
  expansions: 30
  cpuct: 1.5
  rootNoise: 0.5
  drawValue: 0.5

tempDecider:
  name: TemperatureMoveDecider
  explorationPlyCount: 9

selfplayer:
  name: LinearSelfPlayWorker
  initialState: $mnk
  policy: $resnet
  policyIterator: $mcts
  gameCount: 128
  moveDecider: $tempDecider