reporter:
  name: SingleProcessReporter
  windowSize: 20000
  reportsPerIteration: 4000

updater:
  name: SingleProcessUpdater
  trainEpochs: 2

mnk:
  name: MNKGameState
  m: 3
  n: 3
  k: 3

optimizerArgs:
  name: dict
  lr: 0.001
  weight_decay: 0.001

resnet:
  name: PytorchPolicy
  batchSize: 128
  blocks: 1
  filters: 64
  headKernel: 1
  headFilters: 1
  protoState: $mnk
  device: "cuda:0"
  optimizerName: "torch.optim.adamw.AdamW"
  optimizerArgs: $optimizerArgs

mcts:
  name: MctsPolicyIterator
  expansions: 15
  cpuct: 1.5
  rootNoise: 0.2
  drawValue: 0.5

tempDecider:
  name: TemperatureMoveDecider
  explorationPlyCount: 12

selfplayer:
  name: LinearSelfPlayWorker
  initialState: $mnk
  policy: $resnet
  policyIterator: $mcts
  gameCount: 128
  moveDecider: $tempDecider